fango_main_webhook:
    path:     /
    host:     "webhook.fango.me"
    defaults: { _controller: FangoMainBundle:Webhook:index }

fango_main_webhook_email:
    path:     /email
    host:     "webhook.fango.me"
    defaults: { _controller: FangoMainBundle:Webhook:email }

fango_main_homepage:
    path:     /
    defaults: { _controller: FangoMainBundle:Main:index }

fango_main_dashboard:
    path:     /dashboard
    defaults: { _controller: FangoMainBundle:Dashboard:index }

fango_main_dashboard_account_entermail:
    path:     /account/enter_mail
    defaults: { _controller: FangoMainBundle:Account:enterMail }

fango_main_short_link:
    path:     /u/{hash}
    defaults: { _controller: FangoMainBundle:Campaign:shortLink }

fango_dashboard_earnings:
    path:     /earnings
    defaults: { _controller: FangoMainBundle:Dashboard:earnings }

fango_dashboard_payment:
    path:     /payment
    defaults: { _controller: FangoMainBundle:Dashboard:paymentMethod }

fango_network:
    resource: "@FangoMainBundle/Resources/config/routing/network.yml"

fango_campaign:
    resource: "@FangoMainBundle/Resources/config/routing/campaign.yml"

fango_static:
    resource: "@FangoMainBundle/Resources/config/routing/static.yml"
