fos_user_registration_confirmed:
    pattern: /register/confirmed
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: fango_main_dashboard }

fango_user_facebook_login:
    pattern:  /facebook/login
    defaults: { _controller: FangoUserBundle:Facebook:login }

fango_user_facebook_auth:
    pattern:  /facebook/auth
    defaults: { _controller: FangoUserBundle:Facebook:auth }

fango_user_facebook_check:
    pattern:  /facebook/check
    defaults: { _controller: FangoUserBundle:Facebook:check }
